default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: zip_code_development

test:
  <<: *default
  database: zip_code_test

production:
  <<: *default
  database: zip_code_production
